from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PasswordGenerator(object):
    def setupUi(self, PasswordGenerator):
        PasswordGenerator.setObjectName("PasswordGenerator")
        PasswordGenerator.setFixedSize(446, 367)
        PasswordGenerator.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame = QtWidgets.QFrame(PasswordGenerator)
        self.frame.setGeometry(QtCore.QRect(10, 10, 431, 61))
        self.frame.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(6)
        self.frame.setObjectName("frame")
        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.frame_2 = QtWidgets.QFrame(PasswordGenerator)
        self.frame_2.setGeometry(QtCore.QRect(10, 80, 431, 281))
        self.frame_2.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.checkBox_Majuscules = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_Majuscules.setGeometry(QtCore.QRect(20, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.checkBox_Majuscules.setFont(font)
        self.checkBox_Majuscules.setObjectName("checkBox_Majuscules")
        self.checkBox_miniscules = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_miniscules.setGeometry(QtCore.QRect(190, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.checkBox_miniscules.setFont(font)
        self.checkBox_miniscules.setObjectName("checkBox_miniscules")
        self.checkBox_symboles = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_symboles.setGeometry(QtCore.QRect(20, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.checkBox_symboles.setFont(font)
        self.checkBox_symboles.setObjectName("checkBox_symboles")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button_generate = QtWidgets.QPushButton(self.frame_2)
        self.button_generate.setGeometry(QtCore.QRect(110, 100, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_generate.setFont(font)
        self.button_generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_generate.setObjectName("button_generate")
        self.line_Edit_generated_password = QtWidgets.QLineEdit(self.frame_2)
        self.line_Edit_generated_password.setGeometry(QtCore.QRect(160, 130, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.line_Edit_generated_password.setFont(font)
        self.line_Edit_generated_password.setStyleSheet("")
        self.line_Edit_generated_password.setMaxLength(64)
        self.line_Edit_generated_password.setReadOnly(True)
        self.line_Edit_generated_password.setObjectName("line_Edit_generated_password")
        self.button_copy = QtWidgets.QPushButton(self.frame_2)
        self.button_copy.setGeometry(QtCore.QRect(110, 240, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_copy.setFont(font)
        self.button_copy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_copy.setObjectName("button_copy")
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 210, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.progressBar.setFont(font)
        self.progressBar.setMaximum(4)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.checkBox_chiffres = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_chiffres.setGeometry(QtCore.QRect(190, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.checkBox_chiffres.setFont(font)
        self.checkBox_chiffres.setObjectName("checkBox_chiffres")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(180, 65, 61, 21))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setRange(4,64)
        self.spinBox.setValue(12)

        self.retranslateUi(PasswordGenerator)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerator)

    def retranslateUi(self, PasswordGenerator):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerator.setWindowTitle(_translate("PasswordGenerator", "Generateur de mot de passe"))
        self.label_title.setText(_translate("PasswordGenerator", "Générateur de mots de passe sécurisé"))
        self.checkBox_Majuscules.setText(_translate("PasswordGenerator", "majiscules (A-Z)"))
        self.checkBox_miniscules.setText(_translate("PasswordGenerator", "miniscules (a-z)"))
        self.checkBox_symboles.setText(_translate("PasswordGenerator", "symboles"))
        self.label.setText(_translate("PasswordGenerator", "Mot de passe généré :"))
        self.button_generate.setText(_translate("PasswordGenerator", "Générer le mot de passe"))
        self.button_copy.setText(_translate("PasswordGenerator", "Copier le mot de passe"))
        self.label_2.setText(_translate("PasswordGenerator", "Securité du mot de passe :"))
        self.checkBox_chiffres.setText(_translate("PasswordGenerator", "chiffres"))
        self.label_3.setText(_translate("PasswordGenerator", "Nombre des caracteres :"))

